# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WER_app.Review')),
            ],
        ),
    ]
