# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0002_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
