# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0004_auto_20190302_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='static/images/paesano', width_field=200),
        ),
    ]
