# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0005_page_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='Default', max_length=128),
        ),
    ]
