# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0007_auto_20190306_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address',
            field=models.CharField(default='Default', max_length=128),
        ),
        migrations.AddField(
            model_name='page',
            name='closingH',
            field=models.CharField(default='Default', max_length=128),
        ),
        migrations.AddField(
            model_name='page',
            name='openingH',
            field=models.CharField(default='Default', max_length=128),
        ),
    ]
