# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0009_auto_20190306_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='restaurant'),
        ),
    ]
