# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0005_auto_20190306_1134'),
        ('WER_app', '0010_auto_20190306_1110'),
    ]

    operations = [
    ]
