# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0012_auto_20190309_1206'),
        ('WER_app', '0011_merge_20190306_1154'),
    ]

    operations = [
    ]
