# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0013_merge_20190309_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='onCampus',
            field=models.BooleanField(default=False),
        ),
    ]
