# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0013_merge_20190309_1755'),
        ('WER_app', '0013_merge_20190309_2147'),
    ]

    operations = [
    ]
