# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0014_page_oncampus'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='page',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
    ]
