# Generated by Django 2.1.7 on 2019-03-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0014_auto_20190311_1823'),
        ('WER_app', '0015_auto_20190312_1423'),
    ]

    operations = [
    ]
