# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0014_auto_20190311_1823'),
        ('WER_app', '0014_merge_20190310_1809'),
        ('WER_app', '0015_auto_20190312_1423'),
    ]

    operations = [
    ]
