# Generated by Django 2.1.7 on 2019-03-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0016_merge_20190312_1439'),
        ('WER_app', '0016_merge_20190312_1436'),
    ]

    operations = [
    ]
