# Generated by Django 2.1.7 on 2019-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0017_merge_20190312_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
