# Generated by Django 2.1.7 on 2019-03-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0017_merge_20190312_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='page',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='page',
            name='onCampus',
        ),
    ]
