# Generated by Django 2.1.7 on 2019-03-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0018_auto_20190312_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
