# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-12 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0018_auto_20190312_1529'),
        ('WER_app', '0017_merge_20190312_1452'),
    ]

    operations = [
    ]
