# Generated by Django 2.1.7 on 2019-03-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0019_remove_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
