# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-13 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0019_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='page',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='page',
            name='onCampus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
