# Generated by Django 2.1.7 on 2019-03-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WER_app', '0020_review_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
